import { LearningStore, getLocalizedModule, readNotebookZip, type Permission, type LearningResult } from '../../../packages/learning/src/index'
import { createDossier, parseDossier } from '../../../packages/evidence-review/src/index'
import { ENGINE_VERSION, type EngineId } from '../../../packages/evidence-review/src/classification'
import { readPreferences } from '../../../packages/ui-preferences/src/index'
import { mountOrbitPreferences } from './landing-preferences'
import { mountLearningExperiment, learningExperimentParameters } from './learning-experiments'
import { registerFormationTools, unregisterFormationTools } from './learning-webmcp'

const esc=(v:unknown)=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]!))
const tr=(fr:string,en:string,es:string)=>({fr,en,es})[readPreferences().language]
let activeStore:LearningStore|undefined
function getStore(){
  if(activeStore)return activeStore
  let id='ephemeral';try{id='browser-profile'}catch{id=crypto.randomUUID()}
  let storage;try{storage=localStorage}catch{};activeStore=new LearningStore(`public-course:local:${id}`,storage);return activeStore
}
function download(name:string,content:string){const url=URL.createObjectURL(new Blob([content],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)}
function demoDossier(){const d=createDossier();d.example=true;d.title='Exemple contrôlé : conditions de déplacement';d.question='Le point continue-t-il après relâchement dans tous les modes ?';d.axes=['Mouvement animé','Affichage statique'];const scope={subject:'point',property:'movement-after-release',value:'yes',product:'learning-demo',mode:'animated',version:'1'};d.sources=[{id:'demo-animated',title:'Spécification synthétique — animé',url:'https://orbit.securedme.ca/formation/lab/?view=evidence',status:'read',text:'En mode animé, le point continue après relâchement.',version:'1'},{id:'demo-static',title:'Spécification synthétique — statique',url:'https://orbit.securedme.ca/formation/lab/?view=evidence&source=static',status:'read',text:'En mode statique, le point ne continue pas après relâchement.',version:'1'}];d.claims=[{id:'animated',statement:d.sources[0].text!,kind:'reported',disposition:'supported',scopeAttributes:scope,evidence:[{sourceId:'demo-animated',quote:d.sources[0].text!,relation:'supports',scope}]},{id:'static',statement:d.sources[1].text!,kind:'reported',disposition:'supported',scopeAttributes:{...scope,value:'no',mode:'static'},evidence:[{sourceId:'demo-static',quote:d.sources[1].text!,relation:'supports',scope:{...scope,value:'no',mode:'static'}}]}];return d}

export {readNotebookZip} from '../../../packages/learning/src/index'

export async function mountLearningWorkspace(root:HTMLElement){
  const store=getStore(), abort=new AbortController(),signal=abort.signal,registryOwner=Symbol('orbit-learning-workspace-mount')
  const surface=root.querySelector<HTMLElement>('[data-learning-surface]')!,tabs=root.querySelector<HTMLElement>('[data-learning-tabs]')!,select=root.querySelector<HTMLSelectElement>('[data-module]')!,dialog=root.querySelector<HTMLDialogElement>('[data-learning-dialog]')!,file=root.querySelector<HTMLInputElement>('[data-learning-import]')!
  let disposeExperience=()=>{}, selectedArtifact:string|undefined, importMode='artifact', renderedModule=0, renderedView='', renderedLanguage=''
  const drafts=new Map<string,string>()
  const prefs=root.querySelector<HTMLElement>('[data-formation-preferences]')!;const stopPreferences=mountOrbitPreferences(prefs,root)
  const persistenceNotice=document.createElement('p');persistenceNotice.dataset.learningPersistence='';persistenceNotice.className='note';persistenceNotice.setAttribute('role','status');persistenceNotice.setAttribute('aria-live','polite');surface.before(persistenceNotice)
  function renderPersistenceState(){
    const status=store.getPersistenceStatus(),failed=status.state==='failed'||status.state==='unavailable'
    const message=failed?`${tr('La sauvegarde locale n’est pas confirmée. Le travail courant reste en mémoire : exporte la session avant de fermer.','Local saving is not confirmed. Current work remains in memory: export the session before closing.','El guardado local no está confirmado. El trabajo queda en memoria: exporta la sesión antes de cerrar.')} ${status.message??store.persistenceError??''}`:''
    persistenceNotice.hidden=!failed;if(persistenceNotice.textContent!==message)persistenceNotice.textContent=message
    const label=status.state==='saved'?tr('Sauvegarde locale confirmée','Local saving confirmed','Guardado local confirmado'):
      status.state==='awaiting-choice'?tr('Copie locale conservée — choisir restauration ou enregistrement','Existing local copy protected — choose restore or save','Copia local conservada — elegir restaurar o guardar'):
      failed?tr('Session en mémoire — sauvegarde locale indisponible','Session in memory — local saving unavailable','Sesión en memoria — guardado local no disponible'):
      tr('Session en mémoire — exporter avant fermeture','In memory — export before closing','En memoria — exportar antes de cerrar')
    root.querySelector<HTMLElement>('[data-learning-state]')!.textContent=`${label} · r${status.revision}`
  }
  const notice=(text:string)=>{root.querySelector<HTMLElement>('[data-learning-notice]')!.textContent=text;renderPersistenceState()}
  function artifactCommands(id:string){return `<div class="commands"><button type="button" data-verify-artifact="${esc(id)}">${tr('Calculer / comparer SHA-256','Compute / compare SHA-256','Calcular / comparar SHA-256')}</button><button type="button" data-new-artifact-version="${esc(id)}">${tr('Créer une nouvelle version','Create a new version','Crear una nueva versión')}</button></div>`}
  const checked=(result:LearningResult)=>{if(!['READY','PRESENTED'].includes(result.state))throw Error(`${result.state}: ${result.message??''}`);return result}
  const view=()=>new URL(location.href).searchParams.get('view')??(root.dataset.area==='lab'?'mission':'files')
  function route(v:string){const url=new URL(location.href);url.searchParams.set('module',String(store.snapshot().moduleId));url.searchParams.set('view',v);url.searchParams.delete('artifact');history.pushState({},'',url);render();surface.focus()}
  // Both formation pages have the same shell. Keep its session and canvas alive
  // when changing the central surface, without native view-transition promises.
  function syncArea(){root.dataset.area=location.pathname==='/formation/projets/'?'projects':'lab'}
  function localizeShell(){
    const language=readPreferences().language
    document.title=(root.dataset.area==='projects'?tr('Mes projets de formation','My learning projects','Mis proyectos de formación'):tr('Laboratoire de formation','Learning laboratory','Laboratorio de formación'))+' · Orbit.'
    const skip=document.querySelector<HTMLElement>('[data-formation-skip]');if(skip)skip.textContent=skip.dataset[language]??skip.dataset.fr??''
    const attributeKey={fr:'formationAriaFr',en:'formationAriaEn',es:'formationAriaEs'}[language]
    root.querySelectorAll<HTMLElement>('[data-formation-aria-fr]').forEach(element=>element.setAttribute('aria-label',element.dataset[attributeKey]??element.dataset.formationAriaFr??''))
  }
  function render(){
    localizeShell()
    surface.querySelectorAll<HTMLInputElement|HTMLTextAreaElement>('input[name],textarea[name]').forEach(f=>drafts.set(`${renderedModule}:${renderedView}:${f.name}`,f.value));const s=store.snapshot(),m=getLocalizedModule(s.moduleId,readPreferences().language)!
    const views=root.dataset.area==='lab'?[['mission','Mission','Mission','Misión'],['experiment','Expérience','Experiment','Experimento'],['evidence','Preuves','Evidence','Pruebas'],['reflection','Bilan','Reflection','Reflexión']]:[['files','Fichiers','Files','Archivos'],['versions','Versions','Versions','Versiones'],['journal','Journal','Journal','Diario'],['sharing','Partage','Sharing','Compartir']]
    selectedArtifact=new URL(location.href).searchParams.get('artifact')??undefined
    const selected=views.some(v=>v[0]===view())?view():views[0][0]
    tabs.innerHTML=views.map(([id,fr,en,es])=>`<a href="?module=${s.moduleId}&view=${id}" data-view="${id}" ${selected===id?'aria-current="page"':''}>${tr(fr,en,es)}</a>`).join('')
    select.value=String(s.moduleId);renderPersistenceState()
    if(selected==='experiment'&&renderedView===selected&&renderedModule===s.moduleId&&renderedLanguage===readPreferences().language)return
    disposeExperience();disposeExperience=()=>{};renderedModule=s.moduleId;renderedView=selected;renderedLanguage=readPreferences().language
    if(selectedArtifact){const a=s.artifacts.find(a=>a.id===selectedArtifact);surface.innerHTML=a?`<button data-artifact-back>${tr('Retour aux fichiers','Back to files','Volver a archivos')}</button><h1>${esc(a.title)}</h1><p>${esc(a.origin)} · ${esc(a.status)} · v${a.version} · ${esc(a.hashStatus)}</p><p>${esc(a.sha256??tr('Empreinte non calculée','Digest not computed','Huella no calculada'))}</p>${artifactCommands(a.id)}<pre>${esc(a.content)}</pre><p class="note">${tr('Une empreinte identifie le contenu ; elle ne prouve ni son exécution ni sa compréhension. Aucun code importé n’est exécuté ici.','A digest identifies content; it does not prove execution or understanding. Imported code is not executed here.','Una huella identifica el contenido; no prueba ejecución ni comprensión. Aquí no se ejecuta código importado.')}</p>`:'';return}
    if(selected==='mission')surface.innerHTML=`<section class="reading"><h1>${esc(m.title)}</h1><p>${esc(m.objective)}</p><p class="note">120 min ${tr('lecture accompagnée','guided learning','aprendizaje guiado')} · 30 min Colab · 30 min ${tr('bilan','reflection','reflexión')} → 60 min ${tr('avec ton enseignant','with your teacher','con tu docente')}</p><h2>${tr('Critères de revue','Review criteria','Criterios de revisión')}</h2><ul>${m.criteria.map(c=>`<li>${esc(c)}</li>`).join('')}</ul><h2>${tr('Ressources','Resources','Recursos')}</h2><ul>${m.resources.map(r=>`<li><a href="${esc(r.url)}" target="_blank" rel="noopener">${esc(r.title)}</a></li>`).join('')}</ul><div class="commands"><a href="${esc(m.notebook)}" download>${tr('Télécharger le notebook','Download notebook','Descargar notebook')}</a><a href="https://colab.research.google.com/" target="_blank" rel="noopener">${tr('Ouvrir Colab puis importer le carnet','Open Colab and import the notebook','Abrir Colab e importar el cuaderno')}</a></div><p>${tr('Compte Google gratuit, CPU, sans API payante. Une copie Drive est du cloud Google ; partage uniquement le rendu choisi.','Free Google account, CPU, no paid API. A Drive copy is Google cloud; share only selected work.','Cuenta Google gratuita, CPU, sin API de pago. Drive es nube Google; comparte solo el trabajo elegido.')}</p><button data-view="experiment">${tr('Préparer mon expérience','Prepare my experiment','Preparar mi experimento')}</button><h2>${tr('Projet final : 1 h avec ton enseignant pour configurer → 6 h solo → 1 h avec ton enseignant pour clôturer','Final project: 1 h with your teacher to set up → 6 h solo → 1 h with your teacher to close','Proyecto final: 1 h con docente para configurar → 6 h individual → 1 h con docente para cerrar')}</h2><h2>${tr('Transfert','Transfer','Transferencia')}</h2><p>${esc(m.transfer)}</p>${s.moduleId===8?`<h2>${tr('Assembler tes huit productions','Assemble your eight artifacts','Integrar tus ocho producciones')}</h2><a href="/formation/assembly.zip" download>${tr('Squelette et instructions d’assemblage','Scaffold and integration instructions','Plantilla e instrucciones')}</a><p>${tr('Utilise tes vrais exports. Le squelette fourni est attribué ; il ne remplace pas tes fichiers.','Use your actual exports. The supplied scaffold is attributed; it never replaces your files.','Usa tus exportaciones reales. La plantilla se atribuye; nunca sustituye tus archivos.')}</p>`:''}</section>`
    if(selected==='experiment'){
      const config=learningExperimentParameters[s.moduleId-1]
      surface.innerHTML=`<h1>${tr('Prédire, essayer, expliquer','Predict, try, explain','Predecir, probar, explicar')}</h1><p>${esc(m.prediction)}</p><form data-experiment><label>${tr('Ma prédiction avant l’essai','Prediction before the trial','Predicción antes de probar')}<textarea name="prediction" required maxlength="3000"></textarea></label><label>${esc(config.key)}<input name="parameter" type="number" min="${config.min}" max="${config.max}" step="${config.step}" value="${config.initial}"/></label><div class="experiment-stage" data-experiment-stage><button type="button" class="experiment-point" data-experiment-point aria-label="Point déplaçable"></button></div><p data-experiment-observation aria-live="polite"></p><p class="note">${tr('Expérience préparée indépendante du landing. Glisser puis relâcher ; flèches au clavier. Le mode statique fige la scène.','Prepared experiment independent of the landing. Drag and release; keyboard arrows. Static mode freezes the scene.','Experimento independiente del inicio. Arrastrar y soltar; flechas. Modo estático congela la escena.')}</p><label>${tr('Mon observation et son explication','Observation and explanation','Observación y explicación')}<textarea name="explanation" required maxlength="6000"></textarea></label><button type="submit">${tr('Conserver cet essai déclaré','Save this reported trial','Guardar este ensayo declarado')}</button></form>`
      disposeExperience=mountLearningExperiment(surface,s.moduleId,notice)
    }
    if(selected==='evidence'){
      const d=s.evidenceDossier
      surface.innerHTML=`<h1>${tr('Affirmations et portée','Claims and scope','Afirmaciones y alcance')}</h1><p>${tr('T/I/F concerne les preuves. Ces ensembles ne notent pas l’élève et ne sont pas des probabilités.','T/I/F concerns evidence, not learner grades or probabilities.','T/I/F describe pruebas, no notas ni probabilidades.')}</p><div class="commands"><button data-demo>${tr('Charger l’exemple synthétique','Load synthetic example','Cargar ejemplo sintético')}</button><button data-import-evidence>${tr('Importer un dossier de preuves','Import evidence dossier','Importar expediente de pruebas')}</button></div><fieldset><legend>${tr('Choisir un moteur ou une paire','Choose an engine or pair','Elegir motor o pareja')}</legend>${[['baseline','1 · Standard'],['n','2 · T/I/F'],['p','3 · Attributs']].map(([id,title])=>`<label><input type="checkbox" data-engine="${id}" ${s.engineSelection.includes(id as EngineId)?'checked':''}/>${title}</label>`).join('')}</fieldset><button data-evaluate ${!d||!s.engineSelection.length?'disabled':''}>${tr('Évaluer ces mêmes preuves','Evaluate the same evidence','Evaluar las mismas pruebas')}</button><p class="note">${tr('Aucun moteur implicite, aucune moyenne ni gagnant automatique.','No implicit engine, average or automatic winner.','Sin motor implícito, promedio ni ganador automático.')}</p>${d?`<h2>${esc(d.title)}</h2><p>${esc(d.question)}</p>${d.sources.map(x=>`<article><h3>${esc(x.title)}</h3><blockquote>${esc(x.text)}</blockquote><a href="${esc(x.url)}" target="_blank" rel="noopener">${esc(x.url)}</a><p class="note">${d.example?'EXEMPLE SYNTHÉTIQUE · aucune lecture Context revendiquée':'Source enregistrée, statut à examiner'}</p></article>`).join('')}<div class="engine-results" data-evaluations>${s.evaluations.slice(-1).map(e=>`<pre>${esc(JSON.stringify(e,null,2))}</pre>`).join('')}</div>`:''}<h2>Sanity Context</h2><button data-context-outline>${tr('Lire le sommaire réel','Read actual outline','Leer índice real')}</button><pre data-context-result hidden></pre>`
    }
    if(selected==='reflection')surface.innerHTML=`<h1>${tr('Préparer la revue avec ton enseignant','Prepare teacher review','Preparar revisión con docente')}</h1><form data-reflection><label>${tr('Ce que je peux expliquer, l’aide reçue et mes limites','What I can explain, assistance and limits','Qué puedo explicar, ayuda y límites')}<textarea name="text" maxlength="10000" required></textarea></label><label>${tr('Une question pour le webinaire','A question for the webinar','Pregunta para el seminario')}<input name="question" maxlength="1000"/></label><button>${tr('Conserver mon bilan','Save reflection','Guardar reflexión')}</button></form><p class="note">${tr('Exécution, explication et transfert sont examinés séparément. L’assistant peut donner une solution complète.','Execution, explanation and transfer are examined separately. Your assistant may give a complete solution.','Ejecución, explicación y transferencia se revisan por separado. Tu asistente puede dar la solución completa.')}</p>${s.proposals.map(p=>`<article><h2>${esc(p.kind)} · ${esc(p.status)}</h2><pre>${esc(JSON.stringify(p.payload,null,2))}</pre><label>${tr('Justification humaine','Human rationale','Justificación humana')}<textarea data-review-note="${esc(p.id)}"></textarea></label><div class="commands"><button data-review="${esc(p.id)}" data-decision="accepted">${tr('Accepter pour ce travail','Accept for this work','Aceptar este trabajo')}</button><button data-review="${esc(p.id)}" data-decision="needs-work">${tr('Demander une correction','Request correction','Pedir corrección')}</button></div></article>`).join('')}`
    if(selected==='files')surface.innerHTML=`<h1>${tr('Fichiers sélectionnés','Selected files','Archivos seleccionados')}</h1><div class="commands"><button data-import-artifact>${tr('Importer un rendu Colab ou un fichier','Import Colab work or a file','Importar Colab o archivo')}</button><button data-import-session>${tr('Reprendre une session','Resume a session','Restaurar sesión')}</button></div><p class="note">${tr('JSON, ZIP Colab préparé, code ou notes. Le manifeste et les fichiers du ZIP sont contrôlés. Le code importé est affiché, jamais exécuté automatiquement.','JSON, prepared Colab ZIP, code or notes. ZIP manifests and files are checked. Imported code is displayed, never automatically executed.','JSON, ZIP Colab preparado, código o notas. Se comprueban manifiesto y archivos ZIP. No se ejecuta código importado automáticamente.')}</p>${s.artifacts.map(a=>`<article><button data-artifact="${esc(a.id)}">${esc(a.title)}</button><p>${esc(a.origin)} · ${esc(a.status)} · v${a.version} · ${esc(a.hashStatus)}</p>${artifactCommands(a.id)}<label><input type="checkbox" data-share-artifact="${esc(a.id)}" ${s.sharedArtifactIds.includes(a.id)?'checked':''}/>${tr('Partager ce fichier avec mon assistant','Share this file with my assistant','Compartir archivo con asistente')}</label></article>`).join('')}`
    if(selected==='versions')surface.innerHTML=`<h1>${tr('Versions et évaluations','Versions and evaluations','Versiones y evaluaciones')}</h1><p>r${s.revision} · ${esc(s.format)} · ${ENGINE_VERSION}</p><p class="note">${tr('Une nouvelle version conserve l’ancienne et demande son propre choix de partage. Une empreinte n’atteste ni exécution ni compréhension.','A new version preserves the previous one and requires its own sharing choice. A digest certifies neither execution nor understanding.','Una versión nueva conserva la anterior y requiere su propia selección de acceso. La huella no certifica ejecución ni comprensión.')}</p>${s.artifacts.map(a=>`<article><h2>${esc(a.title)}</h2><p>v${a.version} · ${esc(a.sha256??tr('empreinte non calculée','digest not computed','huella no calculada'))} · ${esc(a.hashStatus)}</p>${artifactCommands(a.id)}<button type="button" data-artifact="${esc(a.id)}">${tr('Ouvrir cette version','Open this version','Abrir esta versión')}</button></article>`).join('')}<pre>${esc(JSON.stringify(s.evaluations,null,2))}</pre>`
    if(selected==='journal')surface.innerHTML=`<h1>${tr('Journal choisi','Selected journal','Diario elegido')}</h1>${s.journal.map(j=>`<article><p>${esc(j.text)}</p><p class="note">${esc(j.at)} · ${esc(j.attribution)}</p><label><input type="checkbox" data-share-journal="${esc(j.id)}" ${s.sharedJournalIds.includes(j.id)?'checked':''}/>${tr('Partager cette trace','Share this record','Compartir esta nota')}</label></article>`).join('')}`
    if(selected==='sharing')surface.innerHTML=sharingMarkup(s)
    surface.querySelectorAll<HTMLInputElement|HTMLTextAreaElement>('input[name],textarea[name]').forEach(f=>{const value=drafts.get(`${s.moduleId}:${selected}:${f.name}`);if(value!==undefined)f.value=value})
  }
  function sharingMarkup(s:ReturnType<LearningStore['snapshot']>){return `<section class="reading"><h1>${tr('Choisir ce qui sort de la session','Choose what leaves this session','Elegir qué sale de la sesión')}</h1><p>${tr('Orbit garde le travail en mémoire ou localement avec ton accord. Colab/Drive est du cloud Google. Sanity reçoit uniquement du contenu accepté comme publiable. Aucun accès enseignant par défaut.','Orbit keeps work in memory or locally with consent. Colab/Drive is Google cloud. Sanity receives only explicitly publishable content. No teacher access by default.','Orbit guarda en memoria o localmente con permiso. Colab/Drive es nube Google. Sanity solo recibe contenido publicable. Sin acceso docente por defecto.')}</p>${([['localSave','Conserver localement','Save locally','Guardar localmente'],['agentRead','Autoriser la lecture partagée','Allow shared reading','Autorizar lectura compartida'],['agentPropose','Autoriser les propositions','Allow proposals','Autorizar propuestas'],['engineSelection','Laisser l’assistant choisir les moteurs','Let assistant select engines','Permitir selección de motores'],['teacherShare','Préparer une remise sélectionnée','Prepare selected teacher handoff','Preparar entrega seleccionada']] as string[][]).map(([id,fr,en,es])=>`<label><input type="checkbox" data-permission="${id}" ${s.permissions[id as Permission]?'checked':''}/>${tr(fr,en,es)}</label>`).join('')}<p class="note">${tr('La copie locale est accessible au même profil navigateur. Un import de session ou une révocation retire les partages. La publication Sanity se fait dans le plugin Studio après prévisualisation.','Local copies are accessible to the same browser profile. Session import or revocation removes shares. Sanity publication happens in the Studio plugin after preview.','Copia local accesible al mismo perfil. Importar una sesión o revocar el acceso elimina permisos. Publicación Sanity desde plugin tras vista previa.')}</p><div class="commands"><button data-restore-local>${tr('Restaurer la copie locale','Restore local copy','Restaurar copia local')}</button><button data-save-local>${tr('Enregistrer le travail courant','Save current work','Guardar trabajo actual')}</button><button data-revoke>${tr('Révoquer les accès de l’assistant','Revoke assistant access','Revocar acceso del asistente')}</button><button data-teacher-export>${tr('Exporter les éléments partagés pour l’enseignant','Export shared items for teacher','Exportar elementos compartidos para docente')}</button></div></section>`}
  root.addEventListener('click',async event=>{const el=(event.target as HTMLElement).closest<HTMLElement>('button,a');if(!el)return;try{
    if(el.matches('.formation-header nav a')){event.preventDefault();const url=new URL((el as HTMLAnchorElement).href);url.searchParams.set('module',String(store.snapshot().moduleId));history.pushState({},'',url);syncArea();render();surface.focus();return}
    if(el.dataset.view){event.preventDefault();selectedArtifact=undefined;route(el.dataset.view)}
    if(el.hasAttribute('data-permissions')){dialog.querySelector('[data-dialog-body]')!.innerHTML=sharingMarkup(store.snapshot());dialog.showModal()}
    if(el.hasAttribute('data-dialog-close'))dialog.close()
    if(el.hasAttribute('data-restore-local')){checked(store.restoreLocal());dialog.close();notice(tr('Copie restaurée ; autorisations à renouveler.','Copy restored; renew permissions.','Copia restaurada; renueva permisos.'))}
    if(el.hasAttribute('data-save-local'))checked(store.saveCurrentLocally())
    if(el.hasAttribute('data-export'))download('orbit-learning-session.json',store.exportSession())
    if(el.hasAttribute('data-revoke')){store.revokeAgentAccess();notice(tr('Accès révoqués','Access revoked','Acceso revocado'));dialog.close()}
    if(el.hasAttribute('data-teacher-download')){const s=store.snapshot();if(String(s.revision)!==dialog.dataset.previewRevision)throw Error('STALE_REVISION');const r=checked(store.prepareTeacherExport(s.sharedArtifactIds,s.sharedJournalIds));download('orbit-learning-teacher.json',JSON.stringify(r.data,null,2));dialog.close()}
    if(el.hasAttribute('data-teacher-export')){const s=store.snapshot(),r=checked(store.prepareTeacherExport(s.sharedArtifactIds,s.sharedJournalIds));dialog.querySelector('[data-dialog-body]')!.innerHTML=`<h2>${tr('Remise sélectionnée, aucune transmission automatique','Selected handoff, no automatic transmission','Entrega seleccionada, sin transmisión automática')}</h2><pre>${esc(JSON.stringify(r.data,null,2))}</pre><button data-teacher-download>${tr('Télécharger ce contenu','Download this content','Descargar contenido')}</button>`;dialog.dataset.previewRevision=String(s.revision);dialog.showModal()}
    for(const [attr,mode]of [['data-import-artifact','artifact'],['data-import-session','session'],['data-import-evidence','evidence']])if(el.hasAttribute(attr)){importMode=mode;file.click()}
    if(el.dataset.artifact){const url=new URL(location.href);url.searchParams.set('artifact',el.dataset.artifact);history.pushState({},'',url);render();surface.focus()}
    if(el.dataset.newArtifactVersion){const s=store.snapshot(),artifact=s.artifacts.find(row=>row.id===el.dataset.newArtifactVersion);if(!artifact)throw Error('ARTIFACT_NOT_FOUND');dialog.querySelector('[data-dialog-body]')!.innerHTML=`<h2>${tr('Nouvelle version du fichier','New file version','Nueva versión del archivo')} · ${esc(artifact.title)}</h2><p class="note">${tr('L’ancienne version reste conservée. Ce contenu sera enregistré comme modification déclarée, sans exécution ni partage automatique.','The previous version is preserved. This content is stored as a reported modification, without execution or automatic sharing.','Se conserva la versión anterior. El contenido se guarda como modificación declarada, sin ejecución ni acceso automático.')}</p><form data-artifact-version data-artifact-id="${esc(artifact.id)}" data-expected-revision="${s.revision}"><label>${tr('Contenu de la nouvelle version','New version content','Contenido de la nueva versión')}<textarea name="content" maxlength="512000">${esc(artifact.content)}</textarea></label><button type="submit">${tr('Conserver cette nouvelle version','Save this new version','Guardar esta nueva versión')}</button></form>`;dialog.showModal()}
    if(el.dataset.verifyArtifact){el.setAttribute('disabled','');try{const result=checked(await store.verifyArtifact(el.dataset.verifyArtifact));if(signal.aborted||!root.isConnected)return;notice(result.data?.matches===false?tr('Empreinte différente : le contenu ne correspond pas à la déclaration. Aucune exécution ou compréhension n’est vérifiée.','Digest mismatch: content differs from its declaration. Execution and understanding are not verified.','Huella diferente: el contenido no coincide con lo declarado. No se verifica ejecución ni comprensión.'):tr('SHA-256 calculé ou comparé. Cela identifie le contenu ; l’exécution et la compréhension restent non vérifiées.','SHA-256 computed or compared. This identifies content; execution and understanding remain unverified.','SHA-256 calculado o comparado. Identifica contenido; ejecución y comprensión siguen sin verificar.'))}finally{el.removeAttribute('disabled')}}
    if(el.hasAttribute('data-artifact-back'))route('files')
    if(el.hasAttribute('data-demo'))store.setEvidenceDossier(demoDossier())
    if(el.hasAttribute('data-evaluate'))checked(store.evaluateEngines())
    if(el.hasAttribute('data-context-outline')){const output=surface.querySelector<HTMLElement>('[data-context-result]')!;output.hidden=false;output.textContent='Lecture…';const token=store.beginAgentOperation();try{const response=await fetch('/api/v1/course-context/outline',{credentials:'omit',cache:'no-store',headers:{Accept:'application/json'},signal:AbortSignal.any([signal,AbortSignal.timeout(30000)])});const data=await response.json();if(store.isRevisionCurrent(token.revision)&&output.isConnected)output.textContent=response.ok&&data.state==='READY'?JSON.stringify(data,null,2):`UNAVAILABLE · HTTP ${response.status}`}catch{if(signal.aborted||!output.isConnected)return;output.textContent=tr('Passerelle indisponible — aucune lecture revendiquée','Gateway unavailable — no read claimed','Pasarela no disponible — no se declara lectura')}}
    if(el.dataset.review){const note=surface.querySelector<HTMLTextAreaElement>(`[data-review-note="${CSS.escape(el.dataset.review)}"]`)!.value;checked(store.reviewProposal(el.dataset.review,el.dataset.decision as any,note))}
  }catch(error){notice(tr('Action non appliquée : ','Action not applied: ','Acción no aplicada: ')+(error instanceof Error?error.message:'Erreur'))}},{signal})
  root.addEventListener('change',event=>{const el=event.target as HTMLInputElement;try{if(el.dataset.permission){const r=checked(store.setPermission(el.dataset.permission as Permission,el.checked));if(r.data?.savedCopyAvailable)notice(tr('Une copie locale existe : restaure-la ou choisis explicitement de conserver le travail courant.','A local copy exists: restore it or explicitly save the current work.','Existe una copia local: restáurala o guarda explícitamente el trabajo actual.'))}if(el.dataset.shareArtifact||el.dataset.shareJournal){const s=store.snapshot();const key=el.dataset.shareArtifact?'artifactIds':'journalIds',id=el.dataset.shareArtifact??el.dataset.shareJournal!;const ids=key==='artifactIds'?s.sharedArtifactIds:s.sharedJournalIds;const values=el.checked?[...ids,id]:ids.filter(x=>x!==id);checked(store.shareSelection({artifactIds:s.sharedArtifactIds,journalIds:s.sharedJournalIds,[key]:values}))};if(el.dataset.engine){const values=[...surface.querySelectorAll<HTMLInputElement>('[data-engine]:checked')].map(e=>e.dataset.engine as EngineId);store.setEngineSelection(values,'human')}}catch(error){notice(String(error));render()}},{signal})
  select.addEventListener('change',()=>{store.switchModule(Number(select.value));selectedArtifact=undefined;route(root.dataset.area==='lab'?'mission':'files')},{signal})
  root.addEventListener('submit',event=>{const form=event.target as HTMLFormElement;event.preventDefault();const f=new FormData(form);try{
    if(form.hasAttribute('data-artifact-version')){if(!store.isRevisionCurrent(Number(form.dataset.expectedRevision)))throw Error('STALE_REVISION');const artifact=store.addArtifactVersion(form.dataset.artifactId!,String(f.get('content')??''));dialog.close();const url=new URL(location.href);url.searchParams.set('artifact',artifact.id);history.pushState({},'',url);render();surface.focus();notice(tr('Nouvelle version conservée ; choisis séparément son partage.','New version preserved; choose its sharing separately.','Nueva versión conservada; elige su acceso por separado.'));return}
    if(form.hasAttribute('data-reflection')){store.addJournalEntry({kind:'reflection',text:`${f.get('text')}\nQuestion : ${f.get('question')}`,artifactIds:[]});notice(tr('Bilan conservé dans la session','Reflection kept in session','Reflexión guardada en sesión'))}
    if(form.hasAttribute('data-experiment')){store.recordExperiment({prediction:String(f.get('prediction')),variable:learningExperimentParameters[store.snapshot().moduleId-1].key,initialValue:learningExperimentParameters[store.snapshot().moduleId-1].initial,changedValue:Number(f.get('parameter')),controlledConditions:['Même scène préparée','dt borné','Même navigateur'],procedure:['Prédiction','Glisser puis relâcher','Observer','Expliquer'],observations:[surface.querySelector('[data-experiment-observation]')?.textContent??'',String(f.get('explanation'))],restoration:'Restaurer la valeur initiale indiquée ou rouvrir l’expérience.',limitations:['Observation déclarée ; pas mesure scientifique.'],artifactIds:[]});notice(tr('Essai déclaré conservé','Reported trial saved','Ensayo declarado guardado'))}
  }catch(error){notice(String(error))}},{signal})
  file.addEventListener('change',async()=>{
    const f=file.files?.[0];if(!f)return
    const importedRevision=store.snapshot().revision,mode=importMode,zip=f.name.toLowerCase().endsWith('.zip')
    try{
      if(f.size>8_000_000)throw Error('FILE_TOO_LARGE')
      if(zip&&mode!=='artifact')throw Error('COLAB_ZIP_REQUIRES_ARTIFACT_IMPORT')
      const bundle=zip?await readNotebookZip(f):undefined,raw=bundle?'':await f.text()
      if(signal.aborted||!root.isConnected||!store.isRevisionCurrent(importedRevision))throw Error('STALE_IMPORT')
      if(bundle){checked(store.importColabResult(bundle.result));notice(tr(`Archive contrôlée : ${bundle.fileCount} fichiers et empreintes conservés. Travail déclaré ; exécution et compréhension non vérifiées.`,`Archive checked: ${bundle.fileCount} files and digests preserved. Reported work; execution and understanding unverified.`,`Archivo comprobado: ${bundle.fileCount} archivos y huellas conservados. Trabajo declarado; ejecución y comprensión sin verificar.`))}
      else if(mode==='session'){checked(store.importSession(raw));notice(tr('Session reprise ; autorisations et partages retirés.','Session resumed; permissions and shares withdrawn.','Sesión restaurada; permisos y acceso retirados.'))}
      else if(mode==='evidence'){store.setEvidenceDossier(parseDossier(JSON.parse(raw)));notice(tr('Dossier de preuves importé, à examiner.','Evidence dossier imported for examination.','Expediente de pruebas importado para revisión.'))}
      else{
        if(f.name.toLowerCase().endsWith('.json')){const value=JSON.parse(raw);if(value?.schemaVersion==='orbit-learning-colab-v1')checked(store.importColabResult(value));else store.addArtifact({title:f.name,content:raw,origin:'learner',mediaType:'application/json'})}
        else store.addArtifact({title:f.name,content:raw,origin:'learner',path:f.name})
        notice(tr('Import déclaré, sans exécution ni partage automatique.','Reported import, without execution or automatic sharing.','Importación declarada, sin ejecución ni acceso automático.'))
      }
    }catch(error){notice(String(error))}finally{file.value='';renderPersistenceState()}
  },{signal})
  const initial=new URL(location.href).searchParams.get('module');if(initial&&Number(initial)>=1&&Number(initial)<=8&&Number(initial)!==store.snapshot().moduleId)store.switchModule(Number(initial))
  window.addEventListener('popstate',()=>{syncArea();const id=Number(new URL(location.href).searchParams.get('module'));if(id>=1&&id<=8&&id!==store.snapshot().moduleId)store.switchModule(id);render()},{signal})
  window.addEventListener('orbit:preferences-change',render,{signal})
  const unsubscribe=store.subscribe(render);render()
  const cleanup=()=>{disposeExperience();unsubscribe();stopPreferences();persistenceNotice.remove();delete root.dataset.mounted;abort.abort();unregisterFormationTools(store,registryOwner)}
  document.addEventListener('astro:before-swap',cleanup,{once:true,signal})
  window.addEventListener('pagehide',cleanup,{once:true,signal})
  try{const status=await registerFormationTools(store,{courseOrigin:location.origin,owner:registryOwner,signal});if(signal.aborted||!root.isConnected)return;root.querySelector<HTMLElement>('[data-tools-state]')!.textContent=status==='registered'?'25 WebMCP':tr('WebMCP indisponible · commandes humaines','WebMCP unavailable · human controls','WebMCP no disponible · controles humanos')}catch{if(!signal.aborted&&root.isConnected)root.querySelector<HTMLElement>('[data-tools-state]')!.textContent='WebMCP : erreur explicite'}

}
