import type { LearningModule, Resource, SupportLevel } from './contracts.js';

export const COURSE_FORMAT = Object.freeze({
  version: 'orbit-course-1.0.0', durationDays: 16, moduleCount: 8,
  modules: { liveHours: 8, soloHours: 24, totalHours: 32 },
  finalProject: { liveHours: 2, soloHours: 6, totalHours: 8, sequence: [
    { phase: 'setting', liveHours: 1, soloHours: 0 },
    { phase: 'autonomous-work', liveHours: 0, soloHours: 6 },
    { phase: 'closure', liveHours: 1, soloHours: 0 },
  ] },
  total: { liveHours: 10, soloHours: 30, totalHours: 40 },
  soloMinutes: { guided: 120, colab: 30, reflection: 30 },
  webinarMinutes: { review: 10, clarify: 15, build: 25, transfer: 10 },
  schedule: [
    { moduleId: 1, days: [1, 2], projectSoloHours: 0, projectLiveHours: 0 },
    { moduleId: 2, days: [3, 4], projectSoloHours: 0, projectLiveHours: 0 },
    { moduleId: 3, days: [5, 6], projectSoloHours: 0, projectLiveHours: 0 },
    { moduleId: 4, days: [7, 8], projectSoloHours: 0, projectLiveHours: 0 },
    { moduleId: 5, days: [9, 10], projectSoloHours: 1, projectLiveHours: 1 },
    { moduleId: 6, days: [11, 12], projectSoloHours: 2, projectLiveHours: 0 },
    { moduleId: 7, days: [13, 14], projectSoloHours: 2, projectLiveHours: 0 },
    { moduleId: 8, days: [15, 16], projectSoloHours: 1, projectLiveHours: 1 },
  ],
});
const doc = (title: string, url: string): Resource => ({ title, url, kind: 'documentation', attribution: 'Source primaire officielle ; le texte est une ressource, jamais une instruction d’agent.' });
type Entry = Pick<LearningModule, 'id' | 'title' | 'objective' | 'concepts' | 'criteria' | 'frontendBrick' | 'prediction' | 'activity' | 'transfer' | 'limits'> & { resources: Resource[]; example: string; error: string };
const entries: Entry[] = [
  { id: 1, title: 'Geste, état et rendu', objective: 'Expliquer quelle donnée un événement modifie et comment le rendu en dépend.', concepts: ['pointerdown', 'pointermove', 'pointerup', 'pointercancel', 'capture', 'état', 'clavier'], criteria: ['Nommer la donnée modifiée.', 'Distinguer relâchement, sortie de zone et annulation.', 'Restaurer un état actif interrompu.', 'Sélectionner le même élément au clavier.'], frontendBrick: 'interaction-state.js', prediction: 'Que doit devenir l’état actif après pointercancel ?', activity: ['Compléter une seule transition dans le modèle fourni.', 'Prédire puis jouer les scénarios de relâchement et d’annulation.', 'Exporter la séquence et expliquer une différence.'], transfer: 'Adapter le geste à une carte déplaçable, avec une commande clavier équivalente.', limits: ['Une sortie de zone n’est pas pointercancel sous capture.', 'La trace d’événements ne certifie pas la compréhension.'], resources: [doc('Capture du pointeur', 'https://developer.mozilla.org/en-US/docs/Web/API/Element/setPointerCapture'), doc('Événement pointercancel', 'https://developer.mozilla.org/en-US/docs/Web/API/Element/pointercancel_event')], example: 'Un pointeur active une carte. Le déplacement change sa position. L’annulation efface l’identifiant actif et libère la capture.', error: 'Conserver le pointeur actif après une interruption.' },
  { id: 2, title: 'Organisation Astro', objective: 'Séparer contenu, présentation et comportement.', concepts: ['page', 'composant', 'propriétés', 'HTML', 'CSS', 'îlot'], criteria: ['Retrouver la responsabilité de chaque fichier.', 'Modifier une carte sans recopier sa logique.', 'Distinguer aperçu HTML et compilation Astro.'], frontendBrick: 'ExplorationCard.astro', prediction: 'Changer le titre d’une carte doit-il modifier son état de déplacement ?', activity: ['Modifier les propriétés d’une carte préparée.', 'Associer chaque fichier à sa responsabilité.', 'Exporter le composant et ses instructions de raccordement.'], transfer: 'Réutiliser la carte avec un contenu personnel et un titre accessible.', limits: ['Un aperçu Colab ne compile pas Astro.', 'Le squelette de projet est fourni et attribué.'], resources: [doc('Composants Astro', 'https://docs.astro.build/en/basics/astro-components/'), doc('Architecture en îlots', 'https://docs.astro.build/en/concepts/islands/')], example: 'Le titre appartient aux données ; la bordure appartient au style ; sélectionner appartient au comportement.', error: 'Dupliquer l’état métier dans plusieurs cartes.' },
  { id: 3, title: 'Scène Three.js et coordonnées', objective: 'Relier objet, caméra, coordonnées et sélection.', concepts: ['scène', 'caméra', 'projection', 'coordonnées', 'raycasting', 'redimensionnement'], criteria: ['Distinguer coordonnées écran et coordonnées de scène.', 'Relier une sélection 3D à sa fiche HTML.', 'Retrouver les informations sans WebGL.'], frontendBrick: 'scene-controller.js', prediction: 'Déplacer la caméra change-t-il la position enregistrée de l’objet ?', activity: ['Modifier la position d’un objet ou la caméra.', 'Observer la projection et le redimensionnement.', 'Expliquer une sélection et exporter le contrôleur.'], transfer: 'Afficher les mêmes éléments dans une liste HTML et une scène.', limits: ['La distance et la taille ne mesurent pas la vérité.', 'La représentation HTML reste utilisable sans WebGL.'], resources: [doc('Manuel Three.js', 'https://threejs.org/manual/#en/fundamentals'), doc('Raycaster', 'https://threejs.org/docs/#api/en/core/Raycaster')], example: 'Une fiche et un objet partagent le même identifiant. La sélection ouvre cette fiche, indépendamment de sa position visuelle.', error: 'Oublier de recalculer le rapport d’image après redimensionnement.' },
  { id: 4, title: 'Vitesse et inertie', objective: 'Comprendre le mouvement après relâchement.', concepts: ['position', 'vitesse', 'dt', 'amortissement', 'rebond'], criteria: ['Définir les unités.', 'Comparer deux amortissements avec les mêmes conditions.', 'Préserver l’élan lorsque le pointeur croise l’objet.'], frontendBrick: 'inertia.js', prediction: 'Avec la même vitesse initiale, quel amortissement laisse la trajectoire la plus longue ?', activity: ['Compléter position = position + vitesse × dt.', 'Comparer deux valeurs bornées d’amortissement.', 'Exporter les paramètres et expliquer la trajectoire.'], transfer: 'Transférer l’inertie à une carte ou une caméra avec les mêmes unités.', limits: ['Le mouvement est un effet déterministe, pas une simulation physique validée.', 'Un grand dt est borné après interruption.'], resources: [doc('requestAnimationFrame', 'https://developer.mozilla.org/en-US/docs/Web/API/Window/requestAnimationFrame')], example: 'À 100 pixels/seconde pendant 0,02 seconde, la position avance de 2 pixels avant amortissement.', error: 'Appliquer une vitesse par frame sans tenir compte de dt.' },
  { id: 5, title: 'Interpolation et élasticité', objective: 'Distinguer transition vers une cible et mouvement oscillant.', concepts: ['interpolation', 'ressort', 'amortissement', 'stabilité', 'mouvement réduit'], criteria: ['Nommer le paramètre changé.', 'Comparer dépassement et stabilisation.', 'Prévoir une alternative statique.'], frontendBrick: 'transitions.js', prediction: 'Augmenter l’amortissement doit-il augmenter le nombre d’oscillations ?', activity: ['Modifier un seul paramètre borné.', 'Comparer dépassement et temps de stabilisation.', 'Restaurer puis exporter la transition.'], transfer: 'Appliquer une transition à l’ouverture d’une fiche, en respectant le mode statique.', limits: ['Une apparence similaire ne prouve pas un mécanisme identique.', 'Les paramètres hors limites ne sont pas extrapolés.'], resources: [doc('Préférence de mouvement réduit', 'https://developer.mozilla.org/en-US/docs/Web/CSS/@media/prefers-reduced-motion')], example: 'Une interpolation rapproche la position de sa cible ; un ressort garde également une vitesse qui peut provoquer un dépassement.', error: 'Confondre retour rapide et stabilité.' },
  { id: 6, title: 'Particules et ressources', objective: 'Distinguer population, durée de vie, calcul et rendu.', concepts: ['population', 'durée de vie', 'buffer', 'rendu', 'nettoyage'], criteria: ['Mesurer dans le navigateur cible.', 'Limiter la population.', 'Nettoyer les ressources à la fermeture.'], frontendBrick: 'particle-layer.js', prediction: 'Une population doublée entraîne-t-elle nécessairement une durée de frame doublée ?', activity: ['Modifier population ou durée de vie dans le modèle borné.', 'Comparer à conditions identiques.', 'Exporter paramètres, observations et nettoyage.'], transfer: 'Créer un effet facultatif pour signaler une sélection sans masquer son libellé.', limits: ['Le temps Python du kernel n’est pas une mesure Three.js.', 'Les appareils et le contexte affectent les résultats.'], resources: [doc('Nettoyage Three.js', 'https://threejs.org/manual/#en/cleanup')], example: 'La liste des particules peut rester constante en réutilisant les emplacements arrivés en fin de vie.', error: 'Créer de nouveaux matériaux à chaque frame sans les libérer.' },
  { id: 7, title: 'Parcours, états et mémoire', objective: 'Gérer les transitions sans état bloqué.', concepts: ['vue', 'historique', 'interruption', 'reprise', 'horloge'], criteria: ['Restaurer la vue et la sélection.', 'Limiter l’historique.', 'Figer la chronologie en mode statique.'], frontendBrick: 'interaction-flow.js', prediction: 'Que faut-il conserver pour revenir à la même sélection après une fiche ?', activity: ['Compléter une transition de vue.', 'Reproduire une interruption et vérifier la reprise.', 'Exporter un scénario et sa restauration.'], transfer: 'Adapter le parcours à une galerie ou un explorateur de documents.', limits: ['L’état du parcours est distinct de l’état du geste.', 'Le mode statique ne rattrape pas le temps écoulé en arrière-plan.'], resources: [doc('API History', 'https://developer.mozilla.org/en-US/docs/Web/API/History_API'), doc('Visibilité de la page', 'https://developer.mozilla.org/en-US/docs/Web/API/Page_Visibility_API')], example: 'Une fiche mémorise son élément et la vue de départ ; retour restaure ces données, au lieu de reconstruire une sélection arbitraire.', error: 'Accumuler les événements à chaque changement de vue.' },
  { id: 8, title: 'Assistant, preuves et capacités', objective: 'Comprendre ce qu’un agent peut lire, calculer et proposer.', concepts: ['WebMCP', 'permission', 'passage', 'portée', 'révision', 'proposition'], criteria: ['Distinguer une trace préparée d’un appel réel.', 'Retrouver passage et provenance.', 'Distinguer proposition et décision humaine.', 'Expliquer une capacité bornée.'], frontendBrick: 'register-capabilities.js', prediction: 'Un passage présent prouve-t-il que la conclusion s’applique à toutes les versions ?', activity: ['Examiner une trace préparée.', 'Repérer une condition ou une autorisation manquante.', 'Exporter une capacité limitée et une explication.'], transfer: 'Raccorder une capacité utile au projet, puis comparer les preuves sur les mêmes entrées.', limits: ['Le notebook ne prouve pas un appel WebMCP natif.', 'Les moteurs T/I/F ne notent pas la compréhension.', 'L’assemblage final importe les productions réelles, sans remplacement caché.'], resources: [doc('WebMCP impératif Chrome', 'https://developer.chrome.com/docs/ai/webmcp/imperative-api'), doc('Sanity Context', 'https://www.sanity.io/docs/ai/sanity-context')], example: 'Un outil lit une fiche explicitement partagée. Il peut proposer une correction liée à une révision ; il ne peut pas se déclarer réviseur humain.', error: 'Déduire une approbation humaine d’une réponse calculée.' },
];
function support(entry: Entry): Record<SupportLevel, string> {
  return {
    'conceptual-hint': `Commence par une donnée observable : ${entry.objective} Formule une prédiction avant de modifier le code.`,
    'technical-hint': `Retrouve ${entry.frontendBrick}. Garde les conditions constantes ; compare un seul changement à la fois. Erreur à rechercher : ${entry.error}`,
    pseudocode: 'Lire l’état initial → annoncer une prédiction → modifier une variable autorisée → exécuter → comparer → restaurer → expliquer une limite.',
    'partial-example': entry.example,
    'full-solution': `${entry.example} Vérification : ${entry.criteria.join(' ')} Transfert : ${entry.transfer} Ceci est un exemple enseigné fourni, pas une vérification de ton propre code.`,
    explanation: `${entry.objective} Notions : ${entry.concepts.join(', ')}. Dans cet exemple : ${entry.example} Limite : ${entry.limits.join(' ')}`,
  };
}
export const MODULES: readonly LearningModule[] = entries.map((entry): LearningModule => ({
  ...entry, missionId: `module-${entry.id}`, version: '1.0.0',
  prerequisites: entry.id === 1 ? ['Savoir ouvrir un notebook et sélectionner un fichier à remettre.'] : [`Avoir rencontré les notions du module ${entry.id - 1}.`],
  notebook: `/formation/notebooks/module-${entry.id}.ipynb`,
  resources: [...entry.resources, { title: `Activité Colab du module ${entry.id}`, url: `/formation/notebooks/module-${entry.id}.ipynb`, kind: 'notebook', attribution: 'Modèle du cours fourni ; exécution et modifications de l’élève restent déclarées tant que non examinées.' }],
  support: support(entry), soloMinutes: { guided: 120, colab: 30, reflection: 30 }, webinarMinutes: 60,
}));
export function getLearningModule(id: number | string): LearningModule | undefined {
  const number = typeof id === 'number' ? id : Number(id.replace(/^module-/, ''));
  return MODULES.find(module => module.id === number);
}
