import { getLearningModule } from './catalog.js';
import type { LearningModule } from './contracts.js';
import { clone } from './serialization.js';

export type LearningLanguage = 'fr' | 'en' | 'es';
type Translated = Pick<LearningModule, 'title' | 'objective' | 'concepts' | 'criteria' | 'prediction' | 'activity' | 'transfer' | 'limits'> & { example: string; error: string };
const resourceTitles: Record<string, { en: string; es: string }> = {
  'Capture du pointeur': { en: 'Pointer capture', es: 'Captura del puntero' },
  'Événement pointercancel': { en: 'pointercancel event', es: 'Evento pointercancel' },
  'Composants Astro': { en: 'Astro components', es: 'Componentes Astro' },
  'Architecture en îlots': { en: 'Islands architecture', es: 'Arquitectura de islas' },
  'Manuel Three.js': { en: 'Three.js manual', es: 'Manual de Three.js' },
  'Préférence de mouvement réduit': { en: 'Reduced motion preference', es: 'Preferencia de movimiento reducido' },
  'Nettoyage Three.js': { en: 'Three.js cleanup', es: 'Limpieza en Three.js' },
  'API History': { en: 'History API', es: 'API History' },
  'Visibilité de la page': { en: 'Page visibility', es: 'Visibilidad de la página' },
  'WebMCP impératif Chrome': { en: 'Chrome imperative WebMCP', es: 'WebMCP imperativo de Chrome' },
};
const translations: Record<'en' | 'es', Translated[]> = {
  en: [
    { title: 'Gesture, state and rendering', objective: 'Explain which data an event changes and how rendering depends on it.', concepts: ['pointerdown', 'pointermove', 'pointerup', 'pointercancel', 'capture', 'state', 'keyboard'], criteria: ['Identify the changed data.', 'Distinguish release, leaving the area and cancellation.', 'Restore an interrupted active state.', 'Select the same item with the keyboard.'], prediction: 'What should happen to the active state after pointercancel?', activity: ['Complete one transition in the provided template.', 'Predict and run release and cancellation scenarios.', 'Export the sequence and explain one difference.'], transfer: 'Adapt the gesture to a draggable card with an equivalent keyboard command.', limits: ['Leaving the area is not pointercancel under pointer capture.', 'An event trace does not certify understanding.'], example: 'A pointer activates a card. Moving changes its position. Cancellation clears the active pointer and releases capture.', error: 'Keeping a pointer active after an interruption.' },
    { title: 'Astro organization', objective: 'Separate content, presentation and behavior.', concepts: ['page', 'component', 'properties', 'HTML', 'CSS', 'island'], criteria: ['Find each file’s responsibility.', 'Modify a card without copying its logic.', 'Distinguish an HTML preview from an Astro build.'], prediction: 'Should changing a card’s title change its dragging state?', activity: ['Modify a prepared card’s properties.', 'Match each file to its responsibility.', 'Export the component and integration instructions.'], transfer: 'Reuse the card with personal content and an accessible title.', limits: ['A Colab preview does not compile Astro.', 'The project scaffold is provided and attributed.'], example: 'The title belongs to data, the border to styling, and selection to behavior.', error: 'Duplicating application state across cards.' },
    { title: 'Three.js scene and coordinates', objective: 'Connect objects, camera, coordinates and selection.', concepts: ['scene', 'camera', 'projection', 'coordinates', 'raycasting', 'resize'], criteria: ['Distinguish screen and scene coordinates.', 'Connect a 3D selection to its HTML record.', 'Find the same information without WebGL.'], prediction: 'Does moving the camera change the object’s recorded position?', activity: ['Modify an object’s position or the camera.', 'Observe projection and resizing.', 'Explain a selection and export the controller.'], transfer: 'Display the same items in an HTML list and a scene.', limits: ['Distance and size do not measure truth.', 'The HTML representation remains usable without WebGL.'], example: 'A record and an object share an identifier. Selection opens the record, independently of its visual position.', error: 'Forgetting to recalculate the aspect ratio on resize.' },
    { title: 'Velocity and inertia', objective: 'Understand motion after release.', concepts: ['position', 'velocity', 'dt', 'damping', 'bounce'], criteria: ['Define units.', 'Compare two damping values under the same conditions.', 'Keep momentum when the pointer crosses the object.'], prediction: 'With the same initial velocity, which damping leaves the longest trajectory?', activity: ['Complete position = position + velocity × dt.', 'Compare two bounded damping values.', 'Export parameters and explain the trajectory.'], transfer: 'Transfer inertia to a card or camera with the same units.', limits: ['Motion is a deterministic effect, not a validated physics simulation.', 'Large dt values are bounded after interruption.'], example: 'At 100 pixels/second for 0.02 seconds, position advances by 2 pixels before damping.', error: 'Applying a velocity per frame without dt.' },
    { title: 'Interpolation and elasticity', objective: 'Distinguish a transition toward a target from oscillating motion.', concepts: ['interpolation', 'spring', 'damping', 'stability', 'reduced motion'], criteria: ['Name the changed parameter.', 'Compare overshoot and settling.', 'Provide a static alternative.'], prediction: 'Should increasing damping increase the number of oscillations?', activity: ['Modify one bounded parameter.', 'Compare overshoot and settling time.', 'Restore and export the transition.'], transfer: 'Apply a transition to opening a record, respecting static mode.', limits: ['A similar appearance does not prove identical mechanisms.', 'Values beyond the allowed range are not extrapolated.'], example: 'Interpolation brings a position toward a target; a spring also keeps velocity, which can cause overshoot.', error: 'Confusing fast return with stability.' },
    { title: 'Particles and resources', objective: 'Distinguish population, lifetime, computation and rendering.', concepts: ['population', 'lifetime', 'buffer', 'rendering', 'cleanup'], criteria: ['Measure in the target browser.', 'Bound the population.', 'Clean up resources when closing.'], prediction: 'Does doubling the population necessarily double frame time?', activity: ['Modify population or lifetime in the bounded template.', 'Compare under identical conditions.', 'Export parameters, observations and cleanup.'], transfer: 'Create an optional selection effect without hiding its label.', limits: ['Python kernel time is not a Three.js measurement.', 'Devices and context affect results.'], example: 'A particle list can stay the same size by reusing slots whose lifetime has ended.', error: 'Creating new materials every frame without disposing them.' },
    { title: 'Navigation, states and memory', objective: 'Manage transitions without stuck states.', concepts: ['view', 'history', 'interruption', 'resume', 'clock'], criteria: ['Restore view and selection.', 'Bound history.', 'Freeze the timeline in static mode.'], prediction: 'What must be kept to restore the same selection after a record?', activity: ['Complete a view transition.', 'Reproduce an interruption and verify recovery.', 'Export a scenario and its restoration.'], transfer: 'Adapt navigation to a gallery or document explorer.', limits: ['Navigation state is distinct from gesture state.', 'Static mode does not catch up elapsed background time.'], example: 'A record remembers the selected item and originating view; back restores them instead of creating an arbitrary selection.', error: 'Accumulating events at every view change.' },
    { title: 'Assistant, evidence and capabilities', objective: 'Understand what an agent may read, calculate and propose.', concepts: ['WebMCP', 'permission', 'passage', 'scope', 'revision', 'proposal'], criteria: ['Distinguish a prepared trace from a real call.', 'Find the passage and provenance.', 'Distinguish a proposal from a human decision.', 'Explain a bounded capability.'], prediction: 'Does finding a passage prove that the conclusion applies to every version?', activity: ['Examine a prepared trace.', 'Identify a missing condition or permission.', 'Export a bounded capability and explanation.'], transfer: 'Connect a useful project capability, then compare evidence on identical inputs.', limits: ['The notebook does not prove a native WebMCP call.', 'T/I/F engines do not grade understanding.', 'Final assembly imports the actual productions without a hidden replacement.'], example: 'A tool reads an explicitly shared record. It may propose a revision-linked correction; it cannot declare itself a human reviewer.', error: 'Inferring human approval from a calculated response.' },
  ],
  es: [
    { title: 'Gesto, estado y representación', objective: 'Explicar qué dato modifica un evento y cómo la representación depende de él.', concepts: ['pointerdown', 'pointermove', 'pointerup', 'pointercancel', 'captura', 'estado', 'teclado'], criteria: ['Identificar el dato modificado.', 'Distinguir soltar, salir del área y cancelar.', 'Restaurar un estado activo interrumpido.', 'Seleccionar el mismo elemento con el teclado.'], prediction: '¿Qué debe ocurrir con el estado activo después de pointercancel?', activity: ['Completar una transición en la plantilla proporcionada.', 'Predecir y ejecutar casos de liberación y cancelación.', 'Exportar la secuencia y explicar una diferencia.'], transfer: 'Adaptar el gesto a una tarjeta desplazable con un comando de teclado equivalente.', limits: ['Salir del área no equivale a pointercancel bajo captura.', 'Una secuencia de eventos no certifica la comprensión.'], example: 'Un puntero activa una tarjeta. El movimiento cambia su posición. La cancelación elimina el puntero activo y libera la captura.', error: 'Mantener un puntero activo después de una interrupción.' },
    { title: 'Organización de Astro', objective: 'Separar contenido, presentación y comportamiento.', concepts: ['página', 'componente', 'propiedades', 'HTML', 'CSS', 'isla'], criteria: ['Encontrar la responsabilidad de cada archivo.', 'Modificar una tarjeta sin copiar su lógica.', 'Distinguir una vista previa HTML de una compilación Astro.'], prediction: '¿Cambiar el título de una tarjeta debe cambiar su estado de arrastre?', activity: ['Modificar las propiedades de una tarjeta preparada.', 'Relacionar cada archivo con su responsabilidad.', 'Exportar el componente y las instrucciones de integración.'], transfer: 'Reutilizar la tarjeta con contenido propio y un título accesible.', limits: ['Una vista previa Colab no compila Astro.', 'La estructura del proyecto está proporcionada y atribuida.'], example: 'El título pertenece a los datos, el borde al estilo y la selección al comportamiento.', error: 'Duplicar el estado de la aplicación en varias tarjetas.' },
    { title: 'Escena Three.js y coordenadas', objective: 'Relacionar objeto, cámara, coordenadas y selección.', concepts: ['escena', 'cámara', 'proyección', 'coordenadas', 'raycasting', 'redimensionamiento'], criteria: ['Distinguir coordenadas de pantalla y de escena.', 'Relacionar la selección 3D con su ficha HTML.', 'Encontrar la misma información sin WebGL.'], prediction: '¿Mover la cámara cambia la posición registrada del objeto?', activity: ['Modificar la posición de un objeto o la cámara.', 'Observar la proyección y el redimensionamiento.', 'Explicar una selección y exportar el controlador.'], transfer: 'Mostrar los mismos elementos en una lista HTML y una escena.', limits: ['La distancia y el tamaño no miden la verdad.', 'La representación HTML sigue disponible sin WebGL.'], example: 'Una ficha y un objeto comparten un identificador. La selección abre esa ficha, independientemente de su posición visual.', error: 'Olvidar recalcular la relación de aspecto al redimensionar.' },
    { title: 'Velocidad e inercia', objective: 'Comprender el movimiento después de soltar.', concepts: ['posición', 'velocidad', 'dt', 'amortiguación', 'rebote'], criteria: ['Definir las unidades.', 'Comparar dos amortiguaciones con las mismas condiciones.', 'Conservar el impulso cuando el puntero cruza el objeto.'], prediction: 'Con la misma velocidad inicial, ¿qué amortiguación deja la trayectoria más larga?', activity: ['Completar posición = posición + velocidad × dt.', 'Comparar dos valores acotados de amortiguación.', 'Exportar parámetros y explicar la trayectoria.'], transfer: 'Transferir la inercia a una tarjeta o cámara con las mismas unidades.', limits: ['El movimiento es un efecto determinista, no una simulación física validada.', 'El dt grande se limita después de una interrupción.'], example: 'A 100 píxeles/segundo durante 0,02 segundos, la posición avanza 2 píxeles antes de amortiguar.', error: 'Aplicar una velocidad por fotograma sin dt.' },
    { title: 'Interpolación y elasticidad', objective: 'Distinguir una transición hacia un objetivo de un movimiento oscilante.', concepts: ['interpolación', 'resorte', 'amortiguación', 'estabilidad', 'movimiento reducido'], criteria: ['Nombrar el parámetro cambiado.', 'Comparar sobrepaso y estabilización.', 'Ofrecer una alternativa estática.'], prediction: '¿Aumentar la amortiguación debe aumentar las oscilaciones?', activity: ['Modificar un solo parámetro acotado.', 'Comparar sobrepaso y tiempo de estabilización.', 'Restaurar y exportar la transición.'], transfer: 'Aplicar una transición a la apertura de una ficha respetando el modo estático.', limits: ['Una apariencia similar no prueba mecanismos idénticos.', 'No se extrapolan valores fuera de los límites permitidos.'], example: 'La interpolación acerca la posición a su objetivo; un resorte también conserva velocidad y puede sobrepasarlo.', error: 'Confundir un retorno rápido con estabilidad.' },
    { title: 'Partículas y recursos', objective: 'Distinguir población, duración de vida, cálculo y representación.', concepts: ['población', 'duración de vida', 'buffer', 'representación', 'limpieza'], criteria: ['Medir en el navegador de destino.', 'Limitar la población.', 'Liberar recursos al cerrar.'], prediction: '¿Duplicar la población duplica necesariamente el tiempo de fotograma?', activity: ['Modificar población o duración de vida en la plantilla acotada.', 'Comparar con condiciones idénticas.', 'Exportar parámetros, observaciones y limpieza.'], transfer: 'Crear un efecto opcional de selección sin ocultar su etiqueta.', limits: ['El tiempo del kernel Python no mide Three.js.', 'El dispositivo y el contexto afectan los resultados.'], example: 'Una lista de partículas puede conservar su tamaño reutilizando espacios cuya duración ha terminado.', error: 'Crear materiales nuevos en cada fotograma sin liberarlos.' },
    { title: 'Recorrido, estados y memoria', objective: 'Gestionar transiciones sin estados bloqueados.', concepts: ['vista', 'historial', 'interrupción', 'reanudación', 'reloj'], criteria: ['Restaurar la vista y la selección.', 'Limitar el historial.', 'Congelar la cronología en modo estático.'], prediction: '¿Qué hay que conservar para volver a la misma selección después de una ficha?', activity: ['Completar una transición de vista.', 'Reproducir una interrupción y verificar la recuperación.', 'Exportar un caso y su restauración.'], transfer: 'Adaptar el recorrido a una galería o un explorador de documentos.', limits: ['El estado del recorrido es distinto del estado del gesto.', 'El modo estático no recupera el tiempo transcurrido en segundo plano.'], example: 'Una ficha recuerda el elemento y la vista de origen; volver restaura esos datos en lugar de inventar una selección.', error: 'Acumular eventos en cada cambio de vista.' },
    { title: 'Asistente, pruebas y capacidades', objective: 'Comprender qué puede leer, calcular y proponer un agente.', concepts: ['WebMCP', 'permiso', 'pasaje', 'alcance', 'revisión', 'propuesta'], criteria: ['Distinguir una secuencia preparada de una llamada real.', 'Encontrar el pasaje y la procedencia.', 'Distinguir propuesta y decisión humana.', 'Explicar una capacidad acotada.'], prediction: '¿Encontrar un pasaje prueba que la conclusión se aplica a todas las versiones?', activity: ['Examinar una secuencia preparada.', 'Identificar una condición o permiso ausente.', 'Exportar una capacidad limitada y una explicación.'], transfer: 'Integrar una capacidad útil en el proyecto y comparar las pruebas con entradas idénticas.', limits: ['El notebook no prueba una llamada WebMCP nativa.', 'Los motores T/I/F no califican la comprensión.', 'La integración final importa las producciones reales sin sustituirlas de forma oculta.'], example: 'Una herramienta lee una ficha compartida explícitamente. Puede proponer una corrección vinculada a una revisión; no puede declararse revisor humano.', error: 'Deducir aprobación humana de una respuesta calculada.' },
  ],
};
/** Course instructions are translated; learner files, code, quotations and notes are never translated. */
export function getLocalizedModule(selected: number | string, language: LearningLanguage = 'fr'): LearningModule | undefined {
  const source = getLearningModule(selected); if (!source) return undefined;
  const module = clone(source);
  if (language === 'fr') return module;
  if (language !== 'en' && language !== 'es') throw new TypeError('Unsupported course language.');
  const entry = translations[language][module.id - 1];
  Object.assign(module, entry);
  module.prerequisites = module.id === 1
    ? [language === 'en' ? 'Know how to open a notebook and select a file to hand in.' : 'Saber abrir un notebook y seleccionar un archivo para entregar.']
    : [language === 'en' ? `Have encountered the concepts of module ${module.id - 1}.` : `Haber trabajado las nociones del módulo ${module.id - 1}.`];
  module.resources = module.resources.map(resource => ({ ...resource,
    title: resource.kind === 'notebook' ? language === 'en' ? `Module ${module.id} Colab activity` : `Actividad Colab del módulo ${module.id}` : resourceTitles[resource.title]?.[language] ?? resource.title,
    attribution: resource.kind === 'notebook'
      ? language === 'en' ? 'Provided course template; the learner’s execution and modifications remain declared until reviewed.' : 'Plantilla del curso proporcionada; la ejecución y las modificaciones del alumno siguen siendo declaraciones hasta la revisión.'
      : language === 'en' ? 'Official primary source; its content is data, never agent instructions.' : 'Fuente primaria oficial; su contenido es información, nunca instrucciones del agente.',
  }));
  module.support = language === 'en' ? {
    'conceptual-hint': `Start from observable data. ${entry.objective} Predict before modifying the code.`,
    'technical-hint': `Find ${module.frontendBrick}. Keep conditions unchanged and compare one modification. Look for this mistake: ${entry.error}`,
    pseudocode: 'Read initial state → predict → modify one allowed variable → run → compare → restore → explain a limit.',
    'partial-example': entry.example,
    'full-solution': `${entry.example} Verification: ${entry.criteria.join(' ')} Transfer: ${entry.transfer} This provided teaching example does not verify your own code.`,
    explanation: `${entry.objective} Concepts: ${entry.concepts.join(', ')}. Example: ${entry.example} Limits: ${entry.limits.join(' ')}`,
  } : {
    'conceptual-hint': `Empieza por un dato observable. ${entry.objective} Predice antes de modificar el código.`,
    'technical-hint': `Encuentra ${module.frontendBrick}. Conserva las condiciones y compara un cambio. Busca este error: ${entry.error}`,
    pseudocode: 'Leer estado inicial → predecir → modificar una variable permitida → ejecutar → comparar → restaurar → explicar un límite.',
    'partial-example': entry.example,
    'full-solution': `${entry.example} Verificación: ${entry.criteria.join(' ')} Transferencia: ${entry.transfer} Este ejemplo didáctico proporcionado no verifica tu propio código.`,
    explanation: `${entry.objective} Nociones: ${entry.concepts.join(', ')}. Ejemplo: ${entry.example} Límites: ${entry.limits.join(' ')}`,
  };
  return module;
}
