import { defineField, defineType } from 'sanity'

export const claim = defineType({
  name: 'claim', title: 'Claim', type: 'document',
  fields: [
    defineField({ name: 'statement', type: 'text', rows: 4, validation: (rule) => rule.required().max(800) }),
    defineField({ name: 'status', type: 'string', options: { list: ['confirmed', 'inferred', 'unresolved'] }, validation: (rule) => rule.required() }),
    defineField({ name: 'value', type: 'number', description: 'Optional measured or derived scalar; not a confidence score.' }),
    defineField({ name: 'unit', type: 'string' }),
    defineField({ name: 'qualifier', type: 'string', description: 'Radius convention or simplifying assumptions.' }),
    defineField({
      name: 'confidence',
      type: 'number',
      description: 'Legacy field retained for compatibility. Orbit never converts it into T, I, F, or a truth percentage.',
      validation: (rule) => rule.min(0).max(1),
    }),
    defineField({ name: 'corpus', type: 'reference', to: [{ type: 'researchCorpus' }] }),
    defineField({
      name: 'scopeAttributes',
      title: 'Comparable scope',
      type: 'object',
      description: 'Structured boundary used by Orbit. This does not replace the human-readable qualifier.',
      fields: [
        defineField({ name: 'subject', type: 'string', validation: (rule) => rule.required() }),
        defineField({ name: 'property', type: 'string', validation: (rule) => rule.required() }),
        defineField({ name: 'value', type: 'string', validation: (rule) => rule.required() }),
        defineField({ name: 'provider', type: 'string' }),
        defineField({ name: 'product', type: 'string' }),
        defineField({ name: 'mode', type: 'string' }),
        defineField({ name: 'condition', type: 'string' }),
        defineField({ name: 'version', type: 'string' }),
        defineField({ name: 'effectiveFrom', type: 'date' }),
        defineField({ name: 'effectiveTo', type: 'date' }),
        defineField({ name: 'jurisdiction', type: 'string' }),
        defineField({ name: 'audience', type: 'string' }),
      ],
    }),
    defineField({
      name: 'evidenceLinks',
      title: 'Passage-level evidence',
      type: 'array',
      of: [{
        type: 'object',
        fields: [
          defineField({ name: 'source', type: 'reference', to: [{ type: 'source' }], validation: (rule) => rule.required() }),
          defineField({ name: 'quote', type: 'text', rows: 4, validation: (rule) => rule.required().max(2000) }),
          defineField({ name: 'relation', type: 'string', options: { list: ['supports', 'contradicts', 'contextualizes'] }, validation: (rule) => rule.required() }),
          defineField({ name: 'scopeNote', type: 'string', description: 'Human-readable scope recorded for this exact passage.' }),
          defineField({
            name: 'scopeAttributes',
            title: 'Passage scope',
            type: 'object',
            fields: [
              defineField({ name: 'subject', type: 'string', validation: (rule) => rule.required() }),
              defineField({ name: 'property', type: 'string', validation: (rule) => rule.required() }),
              defineField({ name: 'value', type: 'string', validation: (rule) => rule.required() }),
              defineField({ name: 'provider', type: 'string' }),
              defineField({ name: 'product', type: 'string' }),
              defineField({ name: 'mode', type: 'string' }),
              defineField({ name: 'condition', type: 'string' }),
              defineField({ name: 'version', type: 'string' }),
              defineField({ name: 'effectiveFrom', type: 'date' }),
              defineField({ name: 'effectiveTo', type: 'date' }),
              defineField({ name: 'jurisdiction', type: 'string' }),
              defineField({ name: 'audience', type: 'string' }),
            ],
          }),
        ],
      }],
    }),
    defineField({ name: 'sources', type: 'array', of: [{ type: 'reference', to: [{ type: 'source' }] }], validation: (rule) => rule.min(1) }),
  ],
  preview: { select: { title: 'statement', subtitle: 'status' } },
})
